### ISSUE TITLE
Links in Chapter 1 are not clickable 

### ISSUE THREAD

**Issue by deRemo** [Prabhav10/LaTeX#1]
Hi,

I believe that the links in the Introduction chapter (namely, your LinkedIn profile and this repo) are supposed to be clickable, but they are not (from mobile, at least).

I suggest you to use the hyperref package

**Comment by Prabhav10** [comment]
Hi!

I checked on my phone, and it seems to work. If you don't mind checking, does the email link work? Maybe check the guide on the computer. I used the hyperref package in the .tex file but there might be a bug in my code. Either way, I'll ask a few more people to check and will update the guide accordingly.

Thank you so much @deRemo!

**Comment by deRemo** [comment]
I was using a older version of the pdf, that I've found on LinkedIn. The links on the version I've download from the repo work 👍

**Comment by Prabhav10** [comment]
Ok 👌 Let me know if there are any other issues!
